### ISSUE TITLE
windows 10 Edge?

### ISSUE THREAD

**Issue by endink** [zsxsoft/useragent.js#1]
Windows 10 edge browser can be detected ?

**Comment by zsxsoft** [comment]
Of course.

You can see the comment area of this page: http://blog.zsxsoft.com/post/14


Sent from Outlook Mobile






On Wed, Nov 25, 2015 at 6:06 PM -0800, "endink" <notifications@github.com> wrote:





Windows 10 edge browser can be detected ?

---
Reply to this email directly or view it on GitHub:
https://github.com/zsxsoft/useragent.js/issues/1
