### ISSUE TITLE
能出个ASP.NET版本的不？

### ISSUE THREAD

**Issue by hulang** [zsxsoft/useragent.js#2]
asp,js,php都出了。。求个ASP.NET版本的。

**Comment by zsxsoft** [comment]
NuF
NuGet上应该有类似的库吧，话说回来这个库移植难度也不算很大吧

**Comment by hulang** [comment]
是么？不知道额。。喜欢老大的方式。很清爽。

**Comment by hulang** [comment]
能给个具体的页面么。我去下载看看。

**Comment by zsxsoft** [comment]
我不清楚啊，你自己看看NuGet吧，用几个关键词搜一搜。

另外这代码。。烂爆了

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Oct 20, 2016 at 11:31 AM +0800, "永恒浪子" <notifications@github.com<mailto:notifications@github.com>> wrote:


能给个具体的页面么。我去下载看看。

―
