### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by shelimov** [zsxsoft/useragent.js#4]
Starting with iOS 13, Safari 13 requests desktop versions of sites by default, thus UA string is incorrect. It is possible to detect iOS but navigator.maxTouchPoints, though..

Could you please fix lib, to make an additional check, using navigator.maxTouchPoints and screen resolution (iPad or iPhone)?

**Comment by zsxsoft** [comment]
That's sound interesting, I will check it soon

**Comment by zsxsoft** [comment]
![image](https://user-images.githubusercontent.com/2398785/66281250-0b8a0a80-e8ed-11e9-90d9-1e34070e8fe2.png)

It seems OK? I don't have any iOS device so I used simulator.

**Comment by shelimov** [comment]
Sorry I did a mistake. The problem appears only on iPads. :)

**Comment by zsxsoft** [comment]
![image](https://user-images.githubusercontent.com/2398785/66415697-c2da6a80-ea2e-11e9-9e26-b692280ac0ef.png)

Ah I see. But it's a UserAgent detection library, not a browser detection library. So I can't add this feature, sorry.
